### ISSUE TITLE
Getting back non-proxy objects back

### ISSUE THREAD

**Issue by PowerMogli** [colxi/deep-observer#1] opened 2018-08-04 20:21 UTC
Your solution is great. But there is one thing I have a problem with. The callback is giving me the changed object as proxy but what we really need is the pure JavaScript object. Than we can apply those changes to the item in database. Our problem is that IndexedDb through localforage is not allowing to save proxies. Maybe a WeakMap where you store the mapping from proxy to raw object?

**Comment by colxi** [comment] 2018-08-05 16:46
The callback receives  an `Object`  with the following properties 
- action : String containing one of the following values : add|update|delete
- **object**: Affected property parent's Object
- name: Name of the modified property (or array index)
- oldValue : Value of the property before the change
- keypath : String representing the internal path to the affected property.

The `object` property  contains a **non-proxy object**, however if that object contains nested observed objects, those will be Proxies. I guess that'a your scenario.

But that's the natural behavior of the library, not a bug.

To solve your specific situation, you can use **JSON**, to retrieve a Proxy-free Object:

`JSON.parse( JSON.stringify( yourObserved ) );`

Note: I'm working on a new release, which provides methods for retrieving the original non-proxifed Object, a `resolveKeypath`  and an a `Unobserve ` method. It will be released soon.

**Closed as completed** 2018-08-13 17:32 UTC
